import { Layout } from 'antd'
import { Footer } from 'antd/es/layout/layout'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import CustomHeader from './components/header/HeaderIndex'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'CMS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout className='layout'>
          <div style={{ backgroundColor: 'black' }}>
            <CustomHeader />
          </div>
          {children}
          <div>
            <Footer style={{ textAlign: 'center' }}>Ant Design ©2023 Created by Ant UED</Footer>
          </div>
        </Layout>
      </body>
    </html>
  )
}
